from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from app.database import SessionLocal, engine
from app.models import Base, CallReport

AEST = ZoneInfo("Australia/Sydney")

Base.metadata.create_all(bind=engine)

records = [
    {
        "call_id": "call-1",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=1, hours=2),
        "ended_at": datetime.now(AEST) - timedelta(days=1, hours=1, minutes=55),
        "duration_seconds": 300,
        "cost": 0.45,
        "ended_reason": "customer-ended-call",
        "transcript": "Hello, how can I help you? I want to know your pricing. Sure, our plans start at $99 per month.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer called to inquire about pricing.",
        "success_evaluation": "true",
        "structured_data": {"intent": "pricing"},
    },
    {
        "call_id": "call-2",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=2, hours=3),
        "ended_at": datetime.now(AEST) - timedelta(days=2, hours=2, minutes=50),
        "duration_seconds": 180,
        "cost": 0.30,
        "ended_reason": "customer-ended-call",
        "transcript": "Hi, I want to book an appointment. Sure, when works for you? Tomorrow at 10am. Done.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer booked an appointment for tomorrow at 10am.",
        "success_evaluation": "true",
        "structured_data": {"intent": "booking"},
    },
    {
        "call_id": "call-3",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=3),
        "ended_at": datetime.now(AEST) - timedelta(days=3, minutes=2),
        "duration_seconds": 120,
        "cost": 0.20,
        "ended_reason": "assistant-ended-call",
        "transcript": "Hello. Hello, I cannot hear you. Call dropped.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Call dropped due to poor audio quality.",
        "success_evaluation": "false",
        "structured_data": None,
    },
    {
        "call_id": "call-4",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=5, hours=1),
        "ended_at": datetime.now(AEST) - timedelta(days=5, minutes=50),
        "duration_seconds": 600,
        "cost": 0.90,
        "ended_reason": "customer-ended-call",
        "transcript": "I have a complaint about my last order. I am sorry to hear that. Let me log it for you.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer raised a complaint about their last order.",
        "success_evaluation": "true",
        "structured_data": {"intent": "complaint"},
    },
    {
        "call_id": "call-5",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=7),
        "ended_at": datetime.now(AEST) - timedelta(days=7, minutes=-4),
        "duration_seconds": 240,
        "cost": 0.35,
        "ended_reason": "customer-ended-call",
        "transcript": "What are your business hours? We are open 9am to 5pm Monday to Friday. Thanks.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer asked about business hours.",
        "success_evaluation": "true",
        "structured_data": {"intent": "hours"},
    },
    {
        "call_id": "call-6",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=10, hours=4),
        "ended_at": datetime.now(AEST) - timedelta(days=10, hours=3, minutes=55),
        "duration_seconds": 300,
        "cost": 0.45,
        "ended_reason": "customer-ended-call",
        "transcript": "I want to cancel my subscription. I am sorry to hear that. Done, your subscription is cancelled.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer cancelled their subscription.",
        "success_evaluation": "true",
        "structured_data": {"intent": "cancellation"},
    },
    {
        "call_id": "call-7",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=12),
        "ended_at": datetime.now(AEST) - timedelta(days=12, minutes=-6),
        "duration_seconds": 360,
        "cost": 0.55,
        "ended_reason": "customer-ended-call",
        "transcript": "Do you offer refunds? Yes, within 30 days. Great, I want a refund. Sure, processed.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer requested a refund which was processed.",
        "success_evaluation": "true",
        "structured_data": {"intent": "refund"},
    },
    {
        "call_id": "call-8",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=15, hours=2),
        "ended_at": datetime.now(AEST) - timedelta(days=15, hours=1, minutes=58),
        "duration_seconds": 120,
        "cost": 0.20,
        "ended_reason": "assistant-ended-call",
        "transcript": "I need help with my account. Can you provide your account number? I do not have it. Goodbye.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Could not assist customer as they did not have their account number.",
        "success_evaluation": "false",
        "structured_data": None,
    },
    {
        "call_id": "call-9",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=20),
        "ended_at": datetime.now(AEST) - timedelta(days=20, minutes=-5),
        "duration_seconds": 300,
        "cost": 0.45,
        "ended_reason": "customer-ended-call",
        "transcript": "I want to upgrade my plan. Sure, which plan? The premium one. Done, upgraded.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer upgraded to the premium plan.",
        "success_evaluation": "true",
        "structured_data": {"intent": "upgrade"},
    },
    {
        "call_id": "call-10",
        "org_id": "org-1",
        "assistant_id": "assistant-1",
        "status": "ended",
        "started_at": datetime.now(AEST) - timedelta(days=25, hours=1),
        "ended_at": datetime.now(AEST) - timedelta(days=25, minutes=52),
        "duration_seconds": 480,
        "cost": 0.70,
        "ended_reason": "customer-ended-call",
        "transcript": "I have a technical issue with the app. What is the issue? App not loading. Try reinstalling. Fixed. Thanks.",
        "recording_url": None,
        "stereo_recording_url": None,
        "summary": "Customer had a technical issue with the app, resolved by reinstalling.",
        "success_evaluation": "true",
        "structured_data": {"intent": "technical-support"},
    },
]

db = SessionLocal()
try:
    for data in records:
        record = CallReport(**data)
        db.merge(record)
    db.commit()
    print(f"Seeded {len(records)} records successfully.")
finally:
    db.close()
